import type { Contact } from '../types/contact'

const demoModeEnv = String(import.meta.env.VITE_DEMO_MODE || '').toLowerCase() === 'true'
const demoModeHost =
  typeof window !== 'undefined' &&
  (window.location.hostname.toLowerCase().includes('demo') ||
    window.location.search.toLowerCase().includes('demo=true'))

export const IS_DEMO_MODE = demoModeEnv || demoModeHost

export const DEMO_CONTACTS: Contact[] = [
  {
    id: 'demo-001',
    name: 'Maya Shah',
    title: 'Founder',
    company: 'AURUM STUDIO',
    email: 'maya@aurumstudio.example',
    phone_mobile: '+1 212 555 0148',
    phone_work: '+1 212 555 0199',
    phone_fax: '',
    website: 'aurumstudio.example',
    address: '18 West 24th Street',
    city: 'NEW YORK',
    state: 'NY',
    zip: '10010',
    country: 'USA',
    notes: 'Met at JA New York. Interested in custom bridal line.',
    user_notes: 'Follow up next week with catalog.',
    back_notes: 'Booth B214',
    stars: 4,
    scanned_at: '2026-04-21',
    front_image: '',
    back_image: '',
    front_image_url: '',
    back_image_url: '',
    sent_to_sheets: true,
    created_at: '2026-04-21T14:30:00.000Z',
  },
  {
    id: 'demo-002',
    name: 'Daniel Kim',
    title: 'Wholesale Buyer',
    company: 'NORTHLINE JEWELERS',
    email: 'daniel@northline.example',
    phone_mobile: '+1 415 555 0182',
    phone_work: '',
    phone_fax: '',
    website: 'northline.example',
    address: '420 Market Street',
    city: 'SAN FRANCISCO',
    state: 'CA',
    zip: '94105',
    country: 'USA',
    notes: 'Asked for gemstone price sheet.',
    user_notes: '',
    back_notes: '',
    stars: 3,
    scanned_at: '2026-04-20',
    front_image: '',
    back_image: '',
    front_image_url: '',
    back_image_url: '',
    sent_to_sheets: false,
    created_at: '2026-04-20T18:10:00.000Z',
  },
  {
    id: 'demo-003',
    name: 'Elena Rossi',
    title: 'Creative Director',
    company: 'ROSSI FINE GOLD',
    email: 'elena@rossigold.example',
    phone_mobile: '+39 02 5550 4412',
    phone_work: '',
    phone_fax: '',
    website: 'rossigold.example',
    address: 'Via Monte Napoleone 12',
    city: 'MILAN',
    state: '',
    zip: '20121',
    country: 'ITALY',
    notes: 'International lead. Wants line sheet by email.',
    user_notes: 'High priority.',
    back_notes: '',
    stars: 4,
    scanned_at: '2026-04-19',
    front_image: '',
    back_image: '',
    front_image_url: '',
    back_image_url: '',
    sent_to_sheets: false,
    created_at: '2026-04-19T10:45:00.000Z',
  },
]

export function demoScannedContact(): Contact {
  return {
    id: `demo-scan-${Date.now()}`,
    name: 'Priya Mehta',
    title: 'Sales Director',
    company: 'LOTUS GEMS',
    email: 'priya@lotusgems.example',
    phone_mobile: '+1 646 555 0177',
    phone_work: '+1 646 555 0133',
    phone_fax: '',
    website: 'lotusgems.example',
    address: '36 West 47th Street',
    city: 'NEW YORK',
    state: 'NY',
    zip: '10036',
    country: 'USA',
    notes: 'Demo scan result generated without calling Gemini.',
    user_notes: '',
    back_notes: '',
    stars: 0,
    scanned_at: new Date().toISOString().split('T')[0],
    front_image: '',
    back_image: '',
    front_image_url: '',
    back_image_url: '',
    sent_to_sheets: false,
    created_at: new Date().toISOString(),
  }
}
