import type { Contact } from '../types/contact'

const demoModeEnv = String(import.meta.env.VITE_DEMO_MODE || '').toLowerCase() === 'true'
const demoModeHost =
  typeof window !== 'undefined' &&
  (window.location.hostname.toLowerCase().includes('demo') ||
    window.location.search.toLowerCase().includes('demo=true'))

export const IS_DEMO_MODE = demoModeEnv || demoModeHost

export const DEMO_CONTACTS: Contact[] = [
  {
    id: 'demo-001',
    name: '',
    title: '',
    company: 'GOLD PALACE JEWELERS',
    email: '',
    phone_mobile: '+1 631-475-6899',
    phone_work: '',
    phone_fax: '',
    website: '',
    address: '39 E. Main Street',
    city: 'PATCHOGUE',
    state: 'NY',
    zip: '11772',
    country: 'USA',
    notes: 'Wedding & engagement rings. Brand name watches. Name rings. Chain bracelets. Diamond setting. Special orders made.',
    area: '',
    user_notes: '',
    back_notes: '',
    stars: 0,
    scanned_at: '2026-04-23',
    front_image: '',
    back_image: '',
    front_image_url: '/demo/gold-palace-jewelers.png',
    back_image_url: '',
    sent_to_sheets: false,
    created_at: '2026-04-23T14:30:00.000Z',
  },
  {
    id: 'demo-002',
    name: 'Nicole DeSTEFANO',
    title: '',
    company: 'DAVIDHARVEY FINE JEWELERS',
    email: 'nicoled@davidharvey.com',
    phone_mobile: '',
    phone_work: '+1 203 655 6400',
    phone_fax: '',
    website: 'davidharvey.com',
    address: '995 Post Road',
    city: 'DARIEN',
    state: 'CT',
    zip: '06820',
    country: 'USA',
    notes: '',
    area: '',
    user_notes: '',
    back_notes: '',
    stars: 0,
    scanned_at: '2026-04-23',
    front_image: '',
    back_image: '',
    front_image_url: '/demo/david-harvey.png',
    back_image_url: '',
    sent_to_sheets: false,
    created_at: '2026-04-23T14:20:00.000Z',
  },
  {
    id: 'demo-003',
    name: 'Susan Portanova Rogliano',
    title: 'Designer',
    company: 'HEART OF GOLD FINE JEWELRY, LLC',
    email: 'heartofgoldjwiry@aol.com',
    phone_mobile: '+1 203 323 5312',
    phone_work: '',
    phone_fax: '',
    website: 'heartofgoldfinejewelry.com',
    address: '930 Hope Street',
    city: 'STAMFORD',
    state: 'CT',
    zip: '06907',
    country: 'USA',
    notes: 'Custom Designs, American Craft. Social Media: Facebook: heartofgoldfinejewelry, Instagram: heartofgold_stamford',
    area: '',
    user_notes: '',
    back_notes: '',
    stars: 0,
    scanned_at: '2026-04-23',
    front_image: '',
    back_image: '',
    front_image_url: '/demo/heart-of-gold.png',
    back_image_url: '',
    sent_to_sheets: false,
    created_at: '2026-04-23T14:10:00.000Z',
  },
]

export function demoScannedContact(): Contact {
  return {
    id: `demo-scan-${Date.now()}`,
    name: 'Priya Mehta',
    title: 'Sales Director',
    company: 'LOTUS GEMS',
    email: 'priya@lotusgems.example',
    phone_mobile: '+1 646 555 0177',
    phone_work: '+1 646 555 0133',
    phone_fax: '',
    website: 'lotusgems.example',
    address: '36 West 47th Street',
    city: 'NEW YORK',
    state: 'NY',
    zip: '10036',
    country: 'USA',
    notes: 'Demo scan result generated without calling Gemini.',
    area: '',
    user_notes: '',
    back_notes: '',
    stars: 0,
    scanned_at: new Date().toISOString().split('T')[0],
    front_image: '',
    back_image: '',
    front_image_url: '',
    back_image_url: '',
    sent_to_sheets: false,
    created_at: new Date().toISOString(),
  }
}
